apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: private-isu-portal
  namespace: private-isu-portal
  labels:
    name: private-isu-portal
    role: web
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      name: private-isu-portal
      labels:
        name: private-isu-portal
        role: web
    spec:
      containers:
      - image: quay.io/koudaiii/private-isu-portal:latest
        name: private-isu-portal
        imagePullPolicy: Always
        ports:
        - containerPort: 80
